import requests
from extractor  import extract_all
from transcript import generate_rich_transcript, generate_video_prompt
from comparator import compare_videos

# ── API KEYS ──────────────────────────────────────────
GROQ_API_KEY = "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"


def auto_generate_caption(rich_transcript, groq_api_key):
    """Auto-generate reference caption from rich transcript"""
    print("  Auto-generating reference caption...")
    prompt = f"""Based on this detailed video description, generate ONE concise caption
that summarizes what is happening in the video in 1-2 sentences.

VIDEO DESCRIPTION:
{rich_transcript}

Write ONLY the caption — no extra text, no quotes.
Example: "A person is explaining photosynthesis using diagrams on a whiteboard"
"""
    try:
        response = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {groq_api_key}",
                "Content-Type": "application/json"
            },
            json={
                "model": "llama-3.3-70b-versatile",
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 100,
                "temperature": 0.3
            },
            timeout=15
        )
        if response.status_code == 200:
            caption = response.json()['choices'][0]['message']['content'].strip()
            print(f"  Caption: {caption}")
            return caption
        return "A person is shown in the video performing an activity"
    except Exception as e:
        print(f"  Caption error: {e}")
        return "A person is shown in the video performing an activity"


def run_pipeline(video_path, ground_truth_caption=None):
    """
    Full VidSense pipeline:
    Stage 1 → Speech extraction (Whisper)
    Stage 2 → Visual semantic layers (Groq Vision)
    Stage 3 → Action detection (Groq Vision)
    Stage 4 → Rich transcript generation (Groq LLaMA)
    Stage 5 → Auto-generate reference caption
    Stage 6 → Similarity comparison (SBERT + ROUGE-L)
    """
    print("\n" + "="*55)
    print("  VIDSENSE — VIDEO UNDERSTANDING PIPELINE")
    print("="*55)
    print(f"  Video: {video_path}")
    print("="*55)

    # STAGE 1+2+3: Extract speech + visual + actions
    print("\n=== STAGE 1+2+3: Multimodal Extraction ===")
    extracted = extract_all(video_path, GROQ_API_KEY)
    print(f"  Speech   : {extracted['transcript'][:80]}...")
    print(f"  Language : {extracted['language']}")

    # STAGE 4: Rich transcript
    print("\n=== STAGE 4: Rich Transcript Generation ===")
    rich_transcript = generate_rich_transcript(
        speech         = extracted["transcript"],
        visual_context = extracted["visual_context"],
        actions        = extracted["actions"],
        groq_api_key   = GROQ_API_KEY
    )

    # STAGE 5: Reference caption
    print("\n=== STAGE 5: Reference Caption ===")
    if ground_truth_caption and ground_truth_caption.strip():
        reference_caption = ground_truth_caption.strip()
        caption_source    = "User Provided"
    else:
        reference_caption = auto_generate_caption(rich_transcript, GROQ_API_KEY)
        caption_source    = "Auto-Generated by AI"

    # STAGE 6: Compare
    print("\n=== STAGE 6: Similarity Comparison ===")
    comparison = compare_videos(
        original_video_path  = video_path,
        generated_video_path = None,
        generated_transcript = rich_transcript,
        ground_truth_caption = reference_caption,
        groq_api_key         = GROQ_API_KEY
    )

    print(f"\n  Final Score : {comparison['final_score']}%")
    print(f"  Label       : {comparison['label']}")
    print("\n=== PIPELINE COMPLETE ===")

    return {
        "speech_transcript": extracted["transcript"],
        "language":          extracted["language"],
        "visual_context":    extracted["visual_context"],
        "actions":           extracted["actions"],
        "rich_transcript":   rich_transcript,
        "ground_truth":      reference_caption,
        "caption_source":    caption_source,
        "scores":            comparison,
    }


if __name__ == "__main__":
    import sys
    video  = sys.argv[1] if len(sys.argv) > 1 else "test_video.mp4"
    result = run_pipeline(video)
    scores = result["scores"]
    print(f"\nCaption Source : {result['caption_source']}")
    print(f"Reference      : {result['ground_truth']}")
    print(f"Final Score    : {scores['final_score']}%")
    print(f"Label          : {scores['label']}")


